### ISSUE TITLE
FieldList's data constructor is not exported

### ISSUE THREAD

**Issue by aforemny** [dgvncsz0f/hoauth#12]
Hello,

I am trying to use the hoauth library to access the Twitter API using OAuth. The example given on GitHub is really helpful, however I cannot figure out how to perform 2-legged authentication [1] instead of 3-legged authentication. The main problem appears to be that I cannot construct a Token by myself since FieldList doesn't export its data constructor.

You can manually get an access token for specific applications on [dev.twitter.com](https://dev.twitter.com/), in particular you get the following three pieces of information.

Access token    [ refered to as `accessToken` ]
Access token secret [ refered to as `accessSecret` ]
Access level    Read, write, and direct messages

If FieldList's data constructor were public the following code would be possible.

```
myToken = AccessToken
    { application = app
    , oauthParams = FieldList
        [ ("oauth_token", accessToken)
        , ("oauth_token_secret", accessSecret) ]
    }

directMessages = runOAuthM (fromApplication app) $ do
    putToken myToken
    signRq2 HMACSHA1 Nothing srvUrl >>= serviceRequest CurlClient
```

This is essentially the same as performing a 3-legged authentication and then storing the access token in myToken and reuse it for subsequent connections. However, it might be useful in some cases to construct it yourself, for instance for quick testing or when storing such information in configuration data.

I am definetly not an expert when it comes to OAuth so please correct me if this not an issue of hoauth but an issue of my rudimentary understanding of OAuth.

[1] The term 2-legged authentication might be grossly wrong at this point. In case it is I'd like to apologize for this.

**Comment by dgvncsz0f** [comment]
Hi Alexander,

> The example given on GitHub is really helpful, however I cannot figure out how to perform 2-legged authentication

I guess I should also include an example of 2-legged oauth requests.

Here is an example, suppose you have both app and url defined:

ghci> runOAuthM (fromApplication app) (signRq2 PLAINTEXT Nothing reqUrl >>= serviceRequest CurlClient)

The terminology you are using is correct. You see, 2-legged oauth only
requires your application credentials, so simply using fromApplication
suffices in this case.

You can debug, using nc, if you have it, the oauth request. The actual
cli arguments may vary, though. Make sure you spawn nc before
submitting the request:

ghci> let reqUrl = fromJust . parseURL $ "http://localhost:9999/foobar"
ghci> runOAuthM (fromApplication app) (signRq2 PLAINTEXT Nothing reqUrl >>= serviceRequest CurlClient)

$ nc -l -p 9999
GET /foobar HTTP/1.1
Host: localhost:9999
Accept: _/_
Authorization: OAuth oauth_signature="DiwWKlRsm426JShERhUXInSR76UM5RMy95t6lRro%26",oauth_consumer_key="xMKV5fPwvTcvHiY1mOtf9g",oauth_nonce="WL6qinkxEO9L9UyQCFCRkXHeIRGxql%2Fl1JUklHu%2B5oU%3D",oauth_timestamp="1340827651",oauth_signature_method="PLAINTEXT",oauth_version="1.0",oauth_callback="oob"

Hope that helps. :-)

Best!
~dsouza

**Comment by dgvncsz0f** [comment]
Also, there are a couple of functions you can use to inspect/modify/create a FieldList, they are documented on hackage:

http://hackage.haskell.org/packages/archive/hoauth/0.3.4/doc/html/Network-OAuth-Http-Request.html#g:3

~dsouza

**Comment by aforemny** [comment]
Dear Diego,

first of all thank you for your quick response. I must have missed
these functions somehow. The following function solves the issue I
reported.

```
fromList :: [(String, String)] -> FieldList
```

This function is, as you pointed out, in fact available publicly. So
you can mark my issue as invalid and close. Thanks for the information
and thank you very much for that wonderful library. :-)
