### ISSUE TITLE
UTF8 characters aren't converted to bytestring correctly in response body

### ISSUE THREAD

**Issue by rudyl313** [dgvncsz0f/hoauth#13]
Part of the last line of Network.OAuth.Http.CurlHttpClient is:

```
(B.pack.map (fromIntegral.ord).respBody $ rsp)
```

The problem is the "map (fromIntegral.ord)" function is truncating some UTF8 characters (I noticed the problem with Hebrew chars).

I cloned the repo and tested an alternative variation:

```
(U.fromString . respBody $ rsp) 
```

where U comes from an added import:

```
import qualified Data.ByteString.Lazy.UTF8 as U
```

This fixed the problem for me and it would be greatly appreciated if you could include it in a new version soon (my Haskell driver for the Factual API depends on it). I can also do a pull request if you prefer.

**Comment by dgvncsz0f** [comment]
I've already accepted the pull request killerswan, which fixes this problem. I'll upload the new version to hackage tonight.

**Comment by rudyl313** [comment]
Awesome, thanks @dgvncsz0f and @killerswan

**Comment by rudyl313** [comment]
@dgvncsz0f I haven't seen an update to the hackage package yet

**Comment by dgvncsz0f** [comment]
there you go: hoauth-0.3.5

**Comment by rudyl313** [comment]
Thanks again
