### ISSUE TITLE
not finding System.Crypto.Random?

### ISSUE THREAD

**Issue by killerswan** [dgvncsz0f/hoauth#4]
With the latest commit (and only the latest), I'm not able to build hoauth, and get an error like so (https://gist.github.com/2203932 ):

```
$ cabal-dev -v3 install ./hoauth
...
src/main/haskell/Network/OAuth/Consumer.hs:91:8:
    Could not find module `System.Crypto.Random':
...
```

Not sure what the problem is...

**Comment by dgvncsz0f** [comment]
Hi,

I've accepted a pull request, but it probably was missing to update the cabal file. That should probably fix it.

I should be able to fix it today or so, I'll let you know.

Thanks for reporting this!
~dsouza
