### ISSUE TITLE
hoauth-0.3.3 does not compile

### ISSUE THREAD

**Issue by rudyl313** [dgvncsz0f/hoauth#9]
src/main/haskell/Network/OAuth/Consumer.hs:176:13:
    Not in scope: type constructor or class `R.PrivateKey'
cabal: Error: some packages failed to install:
hoauth-0.3.3 failed during the building phase. The exception was:
ExitFailure 1

**Comment by killerswan** [comment]
This is a result of RSA's updates between 1.2.0.0 and 1.2.0.1, and should already be fixed by commit 3404f64, or in a different way, will be fixed by #10...

PrivateKey is now over in Crypto.Types.PubKey.RSA (crypto-pubkey-types).

**Comment by dgvncsz0f** [comment]
I've uploaded a new version that contains the killerswan patches. You should be able to compile it now against the latest RSA library version.

Thank you!
~dsouza

**Comment by rudyl313** [comment]
Awesome! Thanks for the quick response

**Comment by dgvncsz0f** [comment]
Actually killerswan did all the work! :-)
